---
- hosts: 
    - my_hosts
    - localhost
  roles:
    - role: programs_install
    - role: disk_mount
    - role: samba
    - role: qemu_virsh
      tags: qemu
  become: true
  become_method: sudo
