- name: Restart Rygel service takes time dpending on number of files
  systemd:
    name: rygel.service
    state: restarted
  listen: "Restart Rygel service"

- name: Restart SSH service
  systemd:
    name: sshd
    state: restarted
