- name: Create templates directory
  ansible.builtin.file:
    path: /var/lib/libvirt/images/templates/
    state: directory

- name: Download VM img file
  get_url: 
    url: "{{ item.url }}"
    dest: /var/lib/libvirt/images/templates/{{ item.vm_name }}
  with_items:
    - "{{ ubuntu_24 }}"
    - "{{ ubuntu_26 }}"
